# Generated by Django 4.1.9 on 2023-05-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hitcount', '0004_auto_20200704_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype'),
        ),
    ]
